import { Badge } from "@/components/ui/display";
import { RECOMMENDATION_LABELS, STAGE_LABELS, type MatchType, type Recommendation, type Stage } from "@/lib/domain";

const STAGE_TONES: Record<Stage, "neutral" | "accent" | "success" | "warning" | "danger" | "info"> = {
  interested: "neutral",
  preparing: "neutral",
  applied: "accent",
  recruiter_screen: "info",
  interview: "info",
  final_interview: "info",
  background_checks: "warning",
  offer: "success",
  rejected: "danger",
  withdrawn: "neutral",
  archived: "neutral",
};

export function StageBadge({ stage }: { stage: Stage }) {
  return <Badge tone={STAGE_TONES[stage]}>{STAGE_LABELS[stage]}</Badge>;
}

const REC_TONES: Record<Recommendation, "success" | "accent" | "warning" | "neutral"> = {
  strong_apply: "success",
  apply: "accent",
  stretch: "warning",
  low_value: "neutral",
};

export function RecommendationBadge({ recommendation }: { recommendation: Recommendation }) {
  return <Badge tone={REC_TONES[recommendation]}>{RECOMMENDATION_LABELS[recommendation]}</Badge>;
}

export function FitScore({ score, size = "sm" }: { score: number | null; size?: "sm" | "lg" }) {
  if (score === null) return <span className="text-sm text-muted">Not analysed</span>;
  const tone = score >= 75 ? "text-success" : score >= 55 ? "text-accent" : score >= 35 ? "text-warning" : "text-muted";
  return (
    <span className={size === "lg" ? `text-4xl font-semibold tabular-nums ${tone}` : `text-sm font-semibold tabular-nums ${tone}`}>
      {score}
      <span className="sr-only"> out of 100</span>
      {size === "lg" && <span className="text-base font-normal text-muted" aria-hidden> /100</span>}
    </span>
  );
}

const MATCH_LABELS: Record<MatchType, string> = {
  strong: "Strong match",
  transferable: "Transferable",
  unclear: "Evidence unclear",
  missing: "Missing",
};
const MATCH_TONES: Record<MatchType, "success" | "accent" | "warning" | "danger"> = {
  strong: "success",
  transferable: "accent",
  unclear: "warning",
  missing: "danger",
};

export function MatchBadge({ type }: { type: MatchType }) {
  return <Badge tone={MATCH_TONES[type]}>{MATCH_LABELS[type]}</Badge>;
}

export function ProviderNotice({ provider }: { provider: string }) {
  if (provider !== "mock") return null;
  return (
    <Badge tone="warning" title="Generated by the offline demo provider from templates and your own data. Configure an AI provider for richer output.">
      Demo output (mock AI)
    </Badge>
  );
}
